Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.hostname = "worker1"
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
  end
  config.vm.provision "shell", inline: <<-SHELL
	sed -i '/^127.0.1.1/d' /etc/hosts
	echo "192.168.56.100  master.example.com" >> /etc/hosts
	echo "192.168.56.101  worker1.example.com worker1" >> /etc/hosts
	echo "192.168.56.102  worker2.example.com" >> /etc/hosts

	swapoff -a
	sed -i 's/\(^\/dev\/mapper\/vagrant--vg-swap_1\)/#&/' /etc/fstab

	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
	add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

	curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
	echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

	apt-get update
	apt-get install -y docker-ce=18.06.1~ce~3-0~ubuntu kubelet=1.12.2-00 kubeadm=1.12.2-00 kubectl=1.12.2-00 kubernetes-cni=0.6.0-00
	apt-mark hold docker-ce kubelet kubeadm kubectl

	echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf
	modprobe br_netfilter
	sysctl –p
  SHELL
end
